setupContainers uses docker-machine if found if not defaults to localhost

diff --git a/docker/scripts/setupContainers b/docker/scripts/setupContainers
--- a/docker/scripts/setupContainers
+++ b/docker/scripts/setupContainers
@@ -76,29 +76,21 @@ configure_containers() {
 # this allows us to run docker commands
 #
 enable_docker_env() {
-if [[ ${TRAVIS:-} ]]
-then
-  DOCKERIP=localhost
-  echo "We are in a Travis-CI environment, setting docker IP to $DOCKERIP..."
-elif [[ "$(command -v docker-machine)" && "$(docker-machine ls | grep default)" ]]
-then
-  DOCKERIP=$(docker-machine ip default)
-  echo "found docker-machine, adding it to env and using $DOCKERIP as your docker IP..."
-  eval "$(docker-machine env --shell sh/bash default)"
-elif [[ "$(command -v docker)" && "$(ps aux | grep '[d]ockerd')" ]]
-then
-  DOCKERIP=$(ps -p $(pidof dockerd) -o args --no-headers | awk -F"tcp://" '{print $2}' | cut -d":" -f 1)
-  echo "docker is in your path and you have a docker host running, proceeding with your docker IP set to $DOCKERIP ..."
-elif [[ "$(command -v docker)" ]]
-then
-  DOCKERIP=localhost
-  echo "We found docker in your path, but we are unsure about your docker host, we'll assume your docker IP is $DOCKERIP."
-  echo "But you may need to set up your own docker host, either by using Virtualbox or Docker Toolbox."
-  echo "If you do have a docker host up and running that we can't detect, don't worry things should work just fine."
-else
-  echo "We can't find docker on your system, please install it before running: $0"
-  exit 1
-fi
+  if [[ "$(command -v docker-machine)" && "$(docker-machine ls | grep default)" ]]
+  then
+    DOCKERIP=$(docker-machine ip default)
+    echo "found docker-machine, adding it to env and using $DOCKERIP as your docker IP..."
+    eval "$(docker-machine env --shell sh/bash default)"
+  elif [[ "$(command -v docker)" ]]
+  then
+    DOCKERIP=localhost
+    echo "We found docker in your path, but we are unsure about of your docker host, we'll assume your docker IP is $DOCKERIP."
+    echo "You may need to set up your own docker host, either by using Docker Toolbox or Docker for Mac or something else."
+    echo "If you have a docker host we can't detect, and you usually reach your docker containers via $DOCKERIP, things should work just fine."
+  else
+    echo "We can't find Docker on your system, please install it before running: $0"
+    exit 1
+  fi
 }
 
 find_containers() {
