Cache the MarkLogic binary in travis builds

diff --git a/scripts/installMarkLogic b/scripts/installMarkLogic
--- a/scripts/installMarkLogic
+++ b/scripts/installMarkLogic
@@ -12,7 +12,11 @@ ML_ASSET_PATH="/download/binaries/8.0/MarkLogic-RHEL6-${ML_VERSION}.x86_64.rpm"
 ML_DOWNLOAD_EMAIL="quasarci@slamdata.com"
 ML_DOWNLOAD_PASSWORD="quasarci"
 
-ML_DOCKER_DIR="scripts/marklogic"
+ML_DIR="scripts/marklogic"
+ML_DOCKERFILE="$ML_DIR/Dockerfile"
+ML_DOCKER_DIR="$ML_DIR/docker"
+ML_RPM_SHA1="$ML_DIR/MarkLogic.rpm.sha1"
+ML_RPM_PATH="$ML_DOCKER_DIR/MarkLogic.rpm"
 ML_IMG_NAME="marklogic:${ML_VERSION}"
 ML_CNT_NAME="ml8"
 
@@ -20,14 +24,33 @@ ML_ADMIN_PREFIX="http://localhost:8001/admin/v1"
 ML_USERNAME="marklogic"
 ML_PASSWORD="marklogic"
 
-# Login to developer.marklogic.com
-curl -X POST --data "email=${ML_DOWNLOAD_EMAIL}&password=${ML_DOWNLOAD_PASSWORD}" -c $ML_DEV_COOKIES $ML_DEV_LOGIN
+verify_asset () {
+  sha1sum --status -c $ML_RPM_SHA1
+  echo "$?"
+}
 
-# Obtain a download URL
-ML_DOWNLOAD_PATH="$(curl -X POST --data "download=$ML_ASSET_PATH" -b $ML_DEV_COOKIES $ML_DEV_GET_TOKEN | jq -r '.path')"
+# Create the docker build dir
+mkdir -p $ML_DOCKER_DIR
 
-# Fetch the MarkLogic binary
-curl -o $ML_DOCKER_DIR/MarkLogic.rpm "${ML_DEV_URL}${ML_DOWNLOAD_PATH}"
+# Copy the dockerfile into it
+cp $ML_DOCKERFILE $ML_DOCKER_DIR
+
+if [[ ! -f $ML_RPM_PATH || $(verify_asset) != "0" ]]; then
+  # Login to developer.marklogic.com
+  curl -X POST --data "email=${ML_DOWNLOAD_EMAIL}&password=${ML_DOWNLOAD_PASSWORD}" -c $ML_DEV_COOKIES $ML_DEV_LOGIN
+
+  # Obtain a download URL
+  ML_DOWNLOAD_PATH="$(curl -X POST --data "download=$ML_ASSET_PATH" -b $ML_DEV_COOKIES $ML_DEV_GET_TOKEN | jq -r '.path')"
+
+  # Fetch the MarkLogic binary
+  curl -o $ML_RPM_PATH "${ML_DEV_URL}${ML_DOWNLOAD_PATH}"
+
+  # Ensure checksum matches
+  if [[ $(verify_asset) != "0" ]]; then
+    echo "ERROR: Invalid checksum for $ML_RPM_PATH"
+    exit 1
+  fi
+fi
 
 # Build the docker image
 docker build --rm=true --tag $ML_IMG_NAME $ML_DOCKER_DIR
